'use client';
import {useEffect,useMemo,useState,type FormEvent} from 'react';
import Image from 'next/image';
import axios from 'axios';
import {Activity,Eye,LifeBuoy,LogOut,RefreshCw,Search} from 'lucide-react';
import api from '@/lib/crm/api';
import {AlertBanner,Badge,Btn,Card,PageHeader,Select,StatCard,Table} from '@/components/crm/ui';
interface Tenant{id:string;name:string;email:string;phone:string;status:string;activeMembers:number;staff:number;unresolvedWhatsAppFailures:number;openTickets:number;subscription?:{planName:string;status:string;nextBillingDate?:string}}
interface Overview{data:Tenant[];total:number;generatedAt:string}
interface Ticket{id:string;tenantId:string;title:string;description:string;status:string;severity:string;activity:Array<{at:string;note:string}>;updatedAt:string}
interface Session{id:string;tenantId:string;reason:string;startedAt:string;expiresAt:string;endedAt?:string}
function message(e:unknown){if(axios.isAxiosError(e)){const v=e.response?.data?.message;return Array.isArray(v)?v.join(', '):v||'Request failed';}return'Request failed';}
export default function OpsPage(){const[overview,setOverview]=useState<Overview|null>(null),[tickets,setTickets]=useState<Ticket[]>([]),[sessions,setSessions]=useState<Session[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[tab,setTab]=useState<'tenants'|'tickets'|'sessions'>('tenants'),[ticket,setTicket]=useState({tenantId:'',title:'',description:'',severity:'MEDIUM'}),[impersonate,setImpersonate]=useState({tenantId:'',reason:''});
async function load(query=''){try{const[o,t,s]=await Promise.all([api.get<Overview>('/internal-ops/overview',{params:{search:query||undefined}}),api.get<Ticket[]>('/internal-ops/tickets'),api.get<Session[]>('/internal-ops/impersonation-sessions')]);setOverview(o.data);setTickets(t.data);setSessions(s.data);setError('');}catch(e){setError(message(e));}}
useEffect(()=>{let active=true;void Promise.all([api.get<Overview>('/internal-ops/overview'),api.get<Ticket[]>('/internal-ops/tickets'),api.get<Session[]>('/internal-ops/impersonation-sessions')]).then(([o,t,s])=>{if(active){setOverview(o.data);setTickets(t.data);setSessions(s.data);}}).catch(e=>{if(active)setError(message(e));});return()=>{active=false;};},[]);const tenantNames=useMemo(()=>new Map((overview?.data||[]).map(t=>[t.id,t.name])),[overview]);
async function start(){try{const{data}=await api.post<{session:Session;access_token:string}>('/internal-ops/impersonation-sessions',impersonate);sessionStorage.setItem('fitkalp_support_token',localStorage.getItem('fitkalp_access_token')||'');localStorage.setItem('fitkalp_access_token',data.access_token);setSessions(v=>[data.session,...v]);setNotice('Impersonation is active for one hour. Every request is audited. Use End session to restore support access.');}catch(e){setError(message(e));}}
async function end(session:Session){try{const supportToken=sessionStorage.getItem('fitkalp_support_token');if(supportToken)localStorage.setItem('fitkalp_access_token',supportToken);await api.post(`/internal-ops/impersonation-sessions/${session.id}/end`);sessionStorage.removeItem('fitkalp_support_token');setNotice('Impersonation session ended.');await load();}catch(e){setError(message(e));}}
async function createTicket(e:FormEvent){e.preventDefault();try{await api.post('/internal-ops/tickets',ticket);setTicket({tenantId:'',title:'',description:'',severity:'MEDIUM'});setNotice('Support ticket created.');await load();}catch(x){setError(message(x));}}
async function updateTicket(id:string,status:string){const note=window.prompt('Activity note');if(!note)return;try{await api.patch(`/internal-ops/tickets/${id}`,{status,note});await load();}catch(e){setError(message(e));}}
const activeSessions=sessions.filter(s=>!s.endedAt&&new Date(s.expiresAt)>new Date());return <main style={{padding:24,maxWidth:1500,margin:'auto'}}><div style={{marginBottom:16}}><Image src="/logo.png" alt="FitKalp" width={130} height={45} style={{height:30,width:'auto'}} /></div><PageHeader title="FitKalp Internal Operations" subtitle="Tenant health, support work, and fully audited time-limited impersonation" actions={<Btn variant="secondary" icon={<RefreshCw size={14}/>} onClick={()=>void load(search)}>Refresh</Btn>}/>{error&&<AlertBanner type="error" onClose={()=>setError('')}>{error}</AlertBanner>}{notice&&<AlertBanner type="success" onClose={()=>setNotice('')}>{notice}</AlertBanner>}
<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:14,marginBottom:20}}><StatCard title="Tenants" value={overview?.total||0} icon={<Activity size={18}/>}/><StatCard title="Open tickets" value={tickets.filter(t=>['OPEN','IN_PROGRESS'].includes(t.status)).length} icon={<LifeBuoy size={18}/>} alert={tickets.some(t=>t.severity==='CRITICAL'&&t.status!=='RESOLVED')}/><StatCard title="WhatsApp failures" value={(overview?.data||[]).reduce((n,t)=>n+t.unresolvedWhatsAppFailures,0)} icon={<Activity size={18}/>} /><StatCard title="Active impersonations" value={activeSessions.length} icon={<Eye size={18}/>} alert={activeSessions.length>0}/></div>
<div style={{display:'flex',gap:6,marginBottom:18}}><Btn variant={tab==='tenants'?'primary':'secondary'} onClick={()=>setTab('tenants')}>Tenants</Btn><Btn variant={tab==='tickets'?'primary':'secondary'} onClick={()=>setTab('tickets')}>Tickets</Btn><Btn variant={tab==='sessions'?'primary':'secondary'} onClick={()=>setTab('sessions')}>Impersonation history</Btn></div>
{tab==='tenants'&&<><div style={{display:'flex',gap:8,marginBottom:12}}><input aria-label="Search tenants" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name, email, or phone" style={{padding:9,minWidth:280}}/><Btn icon={<Search size={13}/>} onClick={()=>void load(search)}>Search</Btn></div><Table headers={['Gym','Status','Members','Staff','WA failures','Tickets','Subscription','Support access']} rows={(overview?.data||[]).map(t=>[<div key="g"><strong>{t.name}</strong><br/><small>{t.email} · {t.phone}</small></div>,<Badge key="s" color={t.status==='ACTIVE'?'green':t.status==='PAST_DUE'?'orange':t.status==='SUSPENDED'?'red':'blue'}>{t.status}</Badge>,t.activeMembers,t.staff,t.unresolvedWhatsAppFailures,t.openTickets,t.subscription?`${t.subscription.planName||''} · ${t.subscription.status}`:'None',<Btn key="i" size="sm" onClick={()=>{setImpersonate({tenantId:t.id,reason:''});setTab('sessions');}}>Impersonate</Btn>])}/></>}
{tab==='tickets'&&<div style={{display:'grid',gridTemplateColumns:'minmax(280px,360px) 1fr',gap:16,alignItems:'start'}}><Card title="New support ticket"><form onSubmit={createTicket} style={{display:'grid',gap:8}}><Select value={ticket.tenantId} onChange={tenantId=>setTicket(v=>({...v,tenantId}))} options={[{value:'',label:'Select tenant'},...(overview?.data||[]).map(t=>({value:t.id,label:t.name}))]}/><input required placeholder="Title" value={ticket.title} onChange={e=>setTicket(v=>({...v,title:e.target.value}))} style={{padding:9}}/><textarea required placeholder="Description" value={ticket.description} onChange={e=>setTicket(v=>({...v,description:e.target.value}))} rows={4}/><Select value={ticket.severity} onChange={severity=>setTicket(v=>({...v,severity}))} options={['LOW','MEDIUM','HIGH','CRITICAL'].map(value=>({value,label:value}))}/><Btn type="submit" disabled={!ticket.tenantId}>Create ticket</Btn></form></Card><Table headers={['Tenant','Ticket','Severity','Status','Updated','Actions']} rows={tickets.map(t=>[tenantNames.get(t.tenantId)||t.tenantId,<div key="t"><strong>{t.title}</strong><br/><small>{t.description}</small></div>,<Badge key="v" color={t.severity==='CRITICAL'?'red':t.severity==='HIGH'?'orange':'gray'}>{t.severity}</Badge>,t.status,new Date(t.updatedAt).toLocaleString('en-IN'),<div key="a" style={{display:'flex',gap:5}}>{t.status!=='IN_PROGRESS'&&<Btn size="sm" onClick={()=>void updateTicket(t.id,'IN_PROGRESS')}>Start</Btn>}{!['RESOLVED','CLOSED'].includes(t.status)&&<Btn size="sm" variant="secondary" onClick={()=>void updateTicket(t.id,'RESOLVED')}>Resolve</Btn>}</div>])}/></div>}
{tab==='sessions'&&<><Card title="Start audited support session" subtitle="Requires a reason, expires after one hour, and all subsequent reads and writes are logged"><div style={{display:'grid',gridTemplateColumns:'1fr 2fr auto',gap:8}}><Select value={impersonate.tenantId} onChange={tenantId=>setImpersonate(v=>({...v,tenantId}))} options={[{value:'',label:'Select tenant'},...(overview?.data||[]).map(t=>({value:t.id,label:t.name}))]}/><input value={impersonate.reason} onChange={e=>setImpersonate(v=>({...v,reason:e.target.value}))} placeholder="Reason for access"/><Btn disabled={!impersonate.tenantId||!impersonate.reason} onClick={()=>void start()}>Start</Btn></div></Card><div style={{height:12}}/><Table headers={['Tenant','Reason','Started','Expires','State','Action']} rows={sessions.map(s=>[tenantNames.get(s.tenantId)||s.tenantId,s.reason,new Date(s.startedAt).toLocaleString('en-IN'),new Date(s.expiresAt).toLocaleString('en-IN'),<Badge key="s" color={!s.endedAt&&new Date(s.expiresAt)>new Date()?'orange':'gray'}>{s.endedAt?'ENDED':new Date(s.expiresAt)>new Date()?'ACTIVE':'EXPIRED'}</Badge>,!s.endedAt&&new Date(s.expiresAt)>new Date()?<Btn key="e" variant="danger" size="sm" icon={<LogOut size={12}/>} onClick={()=>void end(s)}>End</Btn>:'-'])}/></>}</main>}
